INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Acupuntura');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Alergia e imunologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Anestesiologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Angiologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cardiologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cirurgia cardiovascular');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cirurgia da mão');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cirurgia de cabeça e pescoço');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cirurgia do aparelho digestivo');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cirurgia geral');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cirurgia oncológica');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cirurgia pediátrica');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cirurgia plástica');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cirurgia torácica');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Cirurgia vascular');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Clínica médica');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Coloproctologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Dermatologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Endocrinologia e metabologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Endoscopia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Gastroenterologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Genética médica');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Geriatria');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Ginecologia e obstetrícia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Hematologia e hemoterapia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Homeopatia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Infectologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Mastologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Medicina de emergência');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Medicina de família e comunidade');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Medicina do trabalho');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Medicina de tráfego');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Medicina esportiva');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Medicina física e reabilitação');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Medicina intensiva');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Medicina legal e perícia médica');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Medicina nuclear');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Medicina preventiva e social');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Nefrologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Neurocirurgia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Neurologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Nutrologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Oftalmologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Oncologia clínica');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Ortopedia e traumatologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Otorrinolaringologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Patologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Patologia clínica/medicina laboratorial');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Pediatria');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Pneumologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Psiquiatria');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Radiologia e diagnóstico por imagem');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Radioterapia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Reumatologia');
INSERT INTO `especialidades_medicas` (`nome_especialidade`) VALUES ('Urologia');

INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Administração em saúde');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Alergia e imunologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Angiorradiologia e cirurgia endovascular');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Atendimento ao queimado');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Cardiologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Cirurgia bariátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Cirurgia crânio-maxilo-facial');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Cirurgia do trauma');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Cirurgia videolaparoscópica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Citopatologia');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Densitometria óssea');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Dor');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Ecocardiografia');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Ecografia vascular com doppler');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Eletrofisiologia clínica invasiva');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Emergência pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Endocrinologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Endoscopia digestiva');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Endoscopia ginecológica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Endoscopia respiratória');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Ergometria');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Estimulação cardíaca eletrônica implantável');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Foniatria');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Gastroenterologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Hansenologia');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Hematologia e hemoterapia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Hemodinâmica e cardiologia intervencionista');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Hepatologia');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Infectologia hospitalar');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Infectologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Mamografia');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Medicina aeroespacial');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Medicina do adolescente');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Medicina do sono');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Medicina fetal');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Medicina intensiva pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Medicina paliativa');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Medicina tropical');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Nefrologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Neonatologia');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Neurofisiologia clínica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Neurologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Neurorradiologia');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Nutrição parenteral e enteral');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Nutrição parenteral e enteral pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Nutrologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Oncologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Pneumologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Psicogeriatria');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Psicoterapia');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Psiquiatria da infância e adolescência');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Psiquiatria forense');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Radiologia intervencionista e angiorradiologia');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Reprodução assistida');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Reumatologia pediátrica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Sexologia');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Toxicologia médica');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Transplante de medula óssea');
INSERT INTO `areas_atuacao_medicas` (`nome_area_atuacao`) VALUES ('Ultrassonografia em ginecologia e obstetrícia');