<template>
  <form method="get">
    <hr />
    <h3 class="text-center">Dados Profissionais</h3>
    <br />
    <div class="form-group row">
      <label for="ufMedico" class="col-sm-2 col-form-label td">UF</label>
      <div class="col-md-2">
        <select class="form-control" id="ufMedico" name="ufMedico">
          <option value="">todas</option>
          <option value="AC">AC</option>
          <option value="AL">AL</option>
          <option value="AM">AM</option>
          <option value="AP">AP</option>
          <option value="BA">BA</option>
          <option value="CE">CE</option>
          <option value="DF">DF</option>
          <option value="ES">ES</option>
          <option value="GO">GO</option>
          <option value="MA">MA</option>
          <option value="MG">MG</option>
          <option value="MT">MT</option>
          <option value="MS">MS</option>
          <option value="PA">PA</option>
          <option value="PB">PB</option>
          <option value="PE">PE</option>
          <option value="PI">PI</option>
          <option value="PR">PR</option>
          <option value="RJ">RJ</option>
          <option value="RN">RN</option>
          <option value="RS">RS</option>
          <option value="RO">RO</option>
          <option value="RR">RR</option>
          <option value="SC">SC</option>
          <option value="SP">SP</option>
          <option value="SE">SE</option>
          <option value="TO">TO</option>
          <option value="BR">BR</option>
        </select>
      </div>
      <label for="ufMedico" class="col-form-label td">CRM</label>
      <div class="col-md-1">
        <input
          type="text"
          class="form-control crm"
          name="crmMedico"
          id="crmMedico"
          value=""
        />
      </div>
      <label for="municipioMedico" class="col-form-label td">Município</label>
      <div class="col-md">
        <select
          class="form-control"
          id="municipioMedico"
          name="municipioMedico"
        >
          <option value="">todas</option>
          <option value="2370">Afonso Cunha</option>
          <option value="2372">Alcântara</option>
          <option value="2373">Aldeias Altas</option>
          <option value="2374">Altamira do Maranhão</option>
          <option value="2375">Alto Alegre do Maranhão</option>
          <option value="2376">Alto Alegre do Pindaré</option>
          <option value="2377">Alto Parnaíba</option>
          <option value="2378">Amapá do Maranhão</option>
          <option value="2379">Amarante do Maranhão</option>
          <option value="2380">Anajatuba</option>
          <option value="2381">Anapurus</option>
          <option value="2382">Anil</option>
          <option value="2383">Apicum-Açu</option>
          <option value="2384">Araguanã</option>
          <option value="2385">Araioses</option>
          <option value="2386">Arame</option>
          <option value="2387">Arari</option>
          <option value="2388">Aurizona</option>
          <option value="2389">Axixá</option>
          <option value="2369">Açailândia</option>
          <option value="2390">Bacabal</option>
          <option value="2391">Bacabeira</option>
          <option value="2392">Bacatuba</option>
          <option value="2393">Bacuri</option>
          <option value="2394">Bacurituba</option>
          <option value="2395">Balsas</option>
          <option value="2398">Barra do Corda</option>
          <option value="2399">Barreirinhas</option>
          <option value="2400">Barro Duro</option>
          <option value="2396">Barão de Grajaú</option>
          <option value="2397">Barão de Tromai</option>
          <option value="2401">Bela Vista do Maranhão</option>
          <option value="2402">Belágua</option>
          <option value="2403">Benedito Leite</option>
          <option value="2404">Bequimão</option>
          <option value="2405">Bernardo do Mearim</option>
          <option value="2406">Boa Vista do Gurupi</option>
          <option value="2407">Boa Vista do Pindaré</option>
          <option value="2408">Bom Jardim</option>
          <option value="2409">Bom Jesus das Selvas</option>
          <option value="2410">Bom Lugar</option>
          <option value="2411">Bonfim do Arari</option>
          <option value="2412">Brejo</option>
          <option value="2413">Brejo de Areia</option>
          <option value="2414">Brejo de São Félix</option>
          <option value="2415">Buriti</option>
          <option value="2416">Buriti Bravo</option>
          <option value="2417">Buriti Cortado</option>
          <option value="2418">Buriticupu</option>
          <option value="2419">Buritirana</option>
          <option value="2420">Cachoeira Grande</option>
          <option value="2421">Cajapió</option>
          <option value="2422">Cajari</option>
          <option value="2423">Campestre do Maranhão</option>
          <option value="2425">Cantanhede</option>
          <option value="2426">Capinzal do Norte</option>
          <option value="2427">Caraíba do Norte</option>
          <option value="2428">Carolina</option>
          <option value="2429">Carutapera</option>
          <option value="2430">Caxias</option>
          <option value="2431">Cedral</option>
          <option value="2432">Central do Maranhão</option>
          <option value="2434">Centro Novo do Maranhão</option>
          <option value="2433">Centro do Guilherme</option>
          <option value="2435">Chapadinha</option>
          <option value="2436">Cidelândia</option>
          <option value="2438">Codozinho</option>
          <option value="2437">Codó</option>
          <option value="2439">Coelho Neto</option>
          <option value="2440">Colinas</option>
          <option value="2441">Conceição do Lago-Açu</option>
          <option value="2442">Coroatá</option>
          <option value="2443">Curupa</option>
          <option value="2444">Cururupu</option>
          <option value="2445">Curva Grande</option>
          <option value="2446">Custódio Lima</option>
          <option value="2424">Cândido Mendes</option>
          <option value="2447">Davinópolis</option>
          <option value="2448">Dom Pedro</option>
          <option value="2449">Duque Bacelar</option>
          <option value="2450">Esperantinópolis</option>
          <option value="2451">Estandarte</option>
          <option value="2452">Estreito</option>
          <option value="2453">Feira Nova do Maranhão</option>
          <option value="2454">Fernando Falcão</option>
          <option value="2455">Formosa da Serra Negra</option>
          <option value="2456">Fortaleza dos Nogueiras</option>
          <option value="2457">Fortuna</option>
          <option value="2458">Frecheiras</option>
          <option value="2459">Godofredo Viana</option>
          <option value="2460">Gonçalves Dias</option>
          <option value="2461">Governador Archer</option>
          <option value="2462">Governador Edison Lobão</option>
          <option value="2463">Governador Eugênio Barros</option>
          <option value="2464">Governador Luiz Rocha</option>
          <option value="2465">Governador Newton Bello</option>
          <option value="2466">Governador Nunes Freire</option>
          <option value="2468">Grajaú</option>
          <option value="2467">Graça Aranha</option>
          <option value="2469">Guimarães</option>
          <option value="2470">Humberto de Campos</option>
          <option value="2471">Ibipira</option>
          <option value="2472">Icatu</option>
          <option value="2474">Igarapé Grande</option>
          <option value="2473">Igarapé do Meio</option>
          <option value="2475">Imperatriz</option>
          <option value="2476">Itaipava do Grajaú</option>
          <option value="2477">Itamataré</option>
          <option value="2478">Itapecuru Mirim</option>
          <option value="2479">Itapera</option>
          <option value="2480">Itinga do Maranhão</option>
          <option value="2481">Jatobá</option>
          <option value="2482">Jenipapo dos Vieiras</option>
          <option value="2484">Joselândia</option>
          <option value="2483">João Lisboa</option>
          <option value="2485">Junco do Maranhão</option>
          <option value="2489">Lago Verde</option>
          <option value="2486">Lago da Pedra</option>
          <option value="2487">Lago do Junco</option>
          <option value="2488">Lago dos Rodrigues</option>
          <option value="2491">Lagoa Grande do Maranhão</option>
          <option value="2490">Lagoa do Mato</option>
          <option value="2492">Lajeado Novo</option>
          <option value="2493">Lapela</option>
          <option value="2494">Leandro</option>
          <option value="2495">Lima Campos</option>
          <option value="2496">Loreto</option>
          <option value="2497">Luís Domingues</option>
          <option value="2498">Magalhães de Almeida</option>
          <option value="2499">Maioba</option>
          <option value="2500">Maracaçumé</option>
          <option value="2501">Marajá do Sena</option>
          <option value="2502">Maranhãozinho</option>
          <option value="2503">Marianópolis</option>
          <option value="2504">Mata</option>
          <option value="2505">Mata Roma</option>
          <option value="2506">Matinha</option>
          <option value="2507">Matões</option>
          <option value="2508">Matões do Norte</option>
          <option value="2509">Milagres do Maranhão</option>
          <option value="2510">Mirador</option>
          <option value="2511">Miranda do Norte</option>
          <option value="2512">Mirinzal</option>
          <option value="2514">Montes Altos</option>
          <option value="2513">Monção</option>
          <option value="2515">Morros</option>
          <option value="2516">Nina Rodrigues</option>
          <option value="2517">Nova Colinas</option>
          <option value="2518">Nova Iorque</option>
          <option value="2519">Nova Olinda do Maranhão</option>
          <option value="2520">Olho D'Água das Cunhãs</option>
          <option value="2521">Olinda Nova do Maranhão</option>
          <option value="2523">Palmeirândia</option>
          <option value="2524">Papagaio</option>
          <option value="2525">Paraibano</option>
          <option value="2526">Parnarama</option>
          <option value="2527">Passagem Franca</option>
          <option value="2528">Pastos Bons</option>
          <option value="2529">Paulino Neves</option>
          <option value="2530">Paulo Ramos</option>
          <option value="2522">Paço do Lumiar</option>
          <option value="2531">Pedreiras</option>
          <option value="2532">Pedro do Rosário</option>
          <option value="2533">Penalva</option>
          <option value="2534">Peri Mirim</option>
          <option value="2535">Peritoró</option>
          <option value="2536">Pimentel</option>
          <option value="2537">Pindaré Mirim</option>
          <option value="2538">Pinheiro</option>
          <option value="2539">Pio XII</option>
          <option value="2540">Pirapemas</option>
          <option value="2543">Porto Franco</option>
          <option value="2544">Porto Rico do Maranhão</option>
          <option value="2542">Porto das Gabarras</option>
          <option value="2541">Poção de Pedras</option>
          <option value="2545">Presidente Dutra</option>
          <option value="2546">Presidente Juscelino</option>
          <option value="2547">Presidente Médici</option>
          <option value="2548">Presidente Sarney</option>
          <option value="2549">Presidente Vargas</option>
          <option value="2550">Primeira Cruz</option>
          <option value="2551">Raposa</option>
          <option value="2552">Resplandes</option>
          <option value="2553">Riachão</option>
          <option value="2554">Ribamar Fiquene</option>
          <option value="2555">Ribeirão Azul</option>
          <option value="2556">Rocado</option>
          <option value="2557">Roque</option>
          <option value="2558">Rosário</option>
          <option value="2559">Sambaíba</option>
          <option value="2560">Santa Filomena do Maranhão</option>
          <option value="2561">Santa Helena</option>
          <option value="2562">Santa Inês</option>
          <option value="2563">Santa Luzia</option>
          <option value="2564">Santa Luzia do Paruá</option>
          <option value="2565">Santa Quitéria do Maranhão</option>
          <option value="2566">Santa Rita</option>
          <option value="2567">Santana do Maranhão</option>
          <option value="2568">Santo Amaro do Maranhão</option>
          <option value="2569">Santo Antônio dos Lopes</option>
          <option value="2597">Satubinha</option>
          <option value="2598">Senador Alexandre Costa</option>
          <option value="2599">Senador La Rocque</option>
          <option value="2600">Serrano do Maranhão</option>
          <option value="2602">Sucupira do Norte</option>
          <option value="2603">Sucupira do Riachão</option>
          <option value="2570">São Benedito do Rio Preto</option>
          <option value="2571">São Bento</option>
          <option value="2572">São Bernardo</option>
          <option value="2573">São Domingos do Azeitão</option>
          <option value="2574">São Domingos do Maranhão</option>
          <option value="2576">São Francisco do Brejão</option>
          <option value="2577">São Francisco do Maranhão</option>
          <option value="2575">São Félix de Balsas</option>
          <option value="2584">São Joaquim dos Melos</option>
          <option value="2585">São José de Ribamar</option>
          <option value="2586">São José dos Basílios</option>
          <option value="2578">São João Batista</option>
          <option value="2579">São João de Cortes</option>
          <option value="2580">São João do Carú</option>
          <option value="2581">São João do Paraíso</option>
          <option value="2582">São João do Soter</option>
          <option value="2583">São João dos Patos</option>
          <option value="2587">São Luís</option>
          <option value="2588">São Luís Gonzaga do Maranhão</option>
          <option value="2589">São Mateus do Maranhão</option>
          <option value="2590">São Pedro da Água Branca</option>
          <option value="2591">São Pedro dos Crentes</option>
          <option value="2592">São Raimundo das Mangabeiras</option>
          <option value="2593">São Raimundo de Codó</option>
          <option value="2594">São Raimundo do Doca Bezerra</option>
          <option value="2595">São Roberto</option>
          <option value="2596">São Vicente Ferrer</option>
          <option value="2601">Sítio Novo</option>
          <option value="2604">Tasso Fragoso</option>
          <option value="2605">Timbiras</option>
          <option value="2606">Timon</option>
          <option value="2607">Trizidela do Vale</option>
          <option value="2608">Tufilândia</option>
          <option value="2609">Tuntum</option>
          <option value="2610">Turiaçu</option>
          <option value="2611">Turilândia</option>
          <option value="2612">Tutóia</option>
          <option value="2613">Urbano Santos</option>
          <option value="2614">Vargem Grande</option>
          <option value="2615">Viana</option>
          <option value="2616">Vila Nova dos Martírios</option>
          <option value="2618">Vitorino Freire</option>
          <option value="2617">Vitória do Mearim</option>
          <option value="2619">Zé Doca</option>
          <option value="2371">Água Doce do Maranhão</option>
        </select>
      </div>
    </div>

    <div class="form-group row">
      <label for="ano" class="col-sm-2 col-form-label td">Especialidade</label>
      <div class="col-md">
        <select
          class="form-control"
          id="especialidadeMedico"
          name="especialidadeMedico"
        >
          <option value="">todas</option>
          <option value="66">ACUPUNTURA</option>
          <option value="97">ADMINISTRAÇÃO EM SAÚDE</option>
          <option value="1">ADMINISTRAÇÃO HOSPITALAR</option>
          <option value="2">ALERGIA E IMUNOLOGIA</option>
          <option value="98">ALERGIA E IMUNOPATOLOGIA</option>
          <option value="84">ANATOMIA PATOLÓGICA</option>
          <option value="3">ANESTESIOLOGIA</option>
          <option value="4">ANGIOLOGIA</option>
          <option value="67">ANGIOLOGIA E CIRURGIA VASCULAR</option>
          <option value="5">BRONCOESOFAGOLOGIA</option>
          <option value="6">CANCEROLOGIA</option>
          <option value="80">CANCEROLOGIA/CANCEROLOGIA CIRÚRGICA</option>
          <option value="81">CANCEROLOGIA/CANCEROLOGIA PEDIÁTRICA</option>
          <option value="7">CARDIOLOGIA</option>
          <option value="8">CIRURGIA CARDIOVASCULAR</option>
          <option value="10">CIRURGIA DA MÃO</option>
          <option value="9">CIRURGIA DE CABEÇA E PESCOÇO</option>
          <option value="99">CIRURGIA DIGESTIVA</option>
          <option value="11">CIRURGIA DO APARELHO DIGESTIVO</option>
          <option value="85">CIRURGIA DO TRAUMA</option>
          <option value="86">CIRURGIA GASTROENTEROLÓGICA</option>
          <option value="12">CIRURGIA GERAL</option>
          <option value="87">CIRURGIA ONCOLÓGICA</option>
          <option value="13">CIRURGIA PEDIÁTRICA</option>
          <option value="14">CIRURGIA PLÁSTICA</option>
          <option value="15">CIRURGIA TORÁCICA</option>
          <option value="110">CIRURGIA TORÁXICA</option>
          <option value="16">CIRURGIA VASCULAR</option>
          <option value="88">CIRURGIA VASCULAR PERIFÉRICA</option>
          <option value="17">CITOPATOLOGIA</option>
          <option value="68">CLÍNICA MÉDICA</option>
          <option value="69">COLOPROCTOLOGIA</option>
          <option value="260">DENSITOMETRIA ÓSSEA</option>
          <option value="18">DERMATOLOGIA</option>
          <option value="83">DIAGNÓSTICO POR IMAGEM</option>
          <option value="89">DOENÇAS INFECCIOSAS E PARASITÁRIAS</option>
          <option value="19">ELETROENCEFALOGRAFIA</option>
          <option value="70">ENDOCRINOLOGIA</option>
          <option value="20">ENDOCRINOLOGIA E METABOLOGIA</option>
          <option value="82">ENDOSCOPIA</option>
          <option value="21">ENDOSCOPIA DIGESTIVA</option>
          <option value="109">ENDOSCOPIA PERORAL</option>
          <option value="101">ENDOSCOPIA PERORAL VIAS AÉREAS</option>
          <option value="22">FISIATRIA</option>
          <option value="23">FONIATRIA</option>
          <option value="24">GASTROENTEROLOGIA</option>
          <option value="25">GENÉTICA CLÍNICA</option>
          <option value="108">GENÉTICA LABORATORIAL</option>
          <option value="71">GENÉTICA MÉDICA</option>
          <option value="26">GERIATRIA</option>
          <option value="90">GERIATRIA E GERONTOLOGIA</option>
          <option value="27">GINECOLOGIA</option>
          <option value="72">GINECOLOGIA E OBSTETRÍCIA</option>
          <option value="28">HANSENOLOGIA</option>
          <option value="29">HEMATOLOGIA</option>
          <option value="73">HEMATOLOGIA E HEMOTERAPIA</option>
          <option value="30">HEMOTERAPIA</option>
          <option value="102">HEPATOLOGIA</option>
          <option value="31">HOMEOPATIA</option>
          <option value="91">IMUNOLOGIA CLÍNICA</option>
          <option value="32">INFECTOLOGIA</option>
          <option value="92">INFORMÁTICA MÉDICA</option>
          <option value="33">MASTOLOGIA</option>
          <option value="261">MEDICINA DE EMERGÊNCIA</option>
          <option value="74">MEDICINA DE FAMÍLIA E COMUNIDADE</option>
          <option value="35">MEDICINA DE TRÁFEGO</option>
          <option value="93">MEDICINA DO ADOLESCENTE</option>
          <option value="103">MEDICINA DO ESPORTE</option>
          <option value="34">MEDICINA DO TRABALHO</option>
          <option value="36">MEDICINA ESPORTIVA</option>
          <option value="75">MEDICINA FÍSICA E REABILITAÇÃO</option>
          <option value="37">MEDICINA GERAL COMUNITÁRIA</option>
          <option value="38">MEDICINA INTENSIVA</option>
          <option value="39">MEDICINA INTERNA OU CLÍNICA MÉDICA</option>
          <option value="40">MEDICINA LEGAL</option>
          <option value="259">MEDICINA LEGAL E PERÍCIA MÉDICA</option>
          <option value="41">MEDICINA NUCLEAR</option>
          <option value="76">MEDICINA PREVENTIVA E SOCIAL</option>
          <option value="42">MEDICINA SANITÁRIA</option>
          <option value="43">NEFROLOGIA</option>
          <option value="44">NEUROCIRURGIA</option>
          <option value="45">NEUROFISIOLOGIA CLÍNICA</option>
          <option value="46">NEUROLOGIA</option>
          <option value="47">NEUROLOGIA PEDIÁTRICA</option>
          <option value="94">NEUROPEDIATRIA</option>
          <option value="104">NUTRIÇÃO PARENTERAL E ENTERAL</option>
          <option value="48">NUTROLOGIA</option>
          <option value="49">OBSTETRÍCIA</option>
          <option value="50">OFTALMOLOGIA</option>
          <option value="95">ONCOLOGIA</option>
          <option value="79">ONCOLOGIA CLÍNICA</option>
          <option value="51">ORTOPEDIA E TRAUMATOLOGIA</option>
          <option value="52">OTORRINOLARINGOLOGIA</option>
          <option value="53">PATOLOGIA</option>
          <option value="54">PATOLOGIA CLÍNICA</option>
          <option value="77">PATOLOGIA CLÍNICA/MEDICINA LABORATORIAL</option>
          <option value="55">PEDIATRIA</option>
          <option value="56">PNEUMOLOGIA</option>
          <option value="105">PNEUMOLOGIA E TISIOLOGIA</option>
          <option value="57">PROCTOLOGIA</option>
          <option value="58">PSIQUIATRIA</option>
          <option value="96">PSIQUIATRIA INFANTIL</option>
          <option value="106">RADIODIAGNÓSTICO</option>
          <option value="59">RADIOLOGIA</option>
          <option value="78">RADIOLOGIA E DIAGNÓSTICO POR IMAGEM</option>
          <option value="60">RADIOTERAPIA</option>
          <option value="61">REUMATOLOGIA</option>
          <option value="62">SEXOLOGIA</option>
          <option value="63">TERAPIA INTENSIVA</option>
          <option value="257">TERAPIA INTENSIVA PEDIÁTRICA</option>
          <option value="64">TISIOLOGIA</option>
          <option value="258">TOCO-GINECOLOGIA</option>
          <option value="107">ULTRASSONOGRAFIA</option>
          <option value="256">
            ULTRASSONOGRAFIA EM GINECOLOGIA E OBSTETRÍCIA
          </option>
          <option value="255">ULTRASSONOGRAFIA GERAL</option>
          <option value="65">UROLOGIA</option>
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label for="ano" class="col-sm-2 col-form-label td"
        >Área de Atuação</label
      >
      <div class="col-md">
        <input
          class="form-control"
          id="areaAtuacaoMedico"
          name="areaAtuacaoMedico"
        />
      </div>
    </div>
  </form>
</template>


<script>
export default {
  mounted() {
    console.log("Component mounted.");
  },
};
</script>